# Assignment No.4

## Numpy 

### Theoretical Questions

In [4]:
# Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
'''
Purpose of Numpy:
1.Effective Data Handling
2.Mathematical Operations
3.Data Analysis

Advantages of Numpy:
1.Performance
2.Memory Efficiency
3.Vectorization


Numpy Enhances Python capabilities by providing:
1.Efficient Multidimensional Arrays: Fast,memory-efficient arrays for handling large datasets.
2.Vectorized Operations: Perform element-wise operations without explicit loops, speeding up calculations.
3.Mathematical Functions: Extensive library of mathematical operations optimized for performance.
4.Integration: Easily integrates with other scientific libraries like SciPy and pandas.
5.Memory Efficiency: Uses less memory than Python lists, making it ideal for large datasets.
    
>>These features make NumPy essential for scientific computing and data analysis in Python.

'''

'\nPurpose of Numpy:\n1.Effective Data Handling\n2.Mathematical Operations\n3.Data Analysis\n\nAdvantages of Numpy:\n1.Performance\n2.Memory Efficiency\n3.Vectorization\n\n\nNumpy Enhances Python capabilities by providing:\n1.Efficient Multidimensional Arrays: Fast,memory-efficient arrays for handling large datasets.\n2.Vectorized Operations: Perform element-wise operations without explicit loops, speeding up calculations.\n3.Mathematical Functions: Extensive library of mathematical operations optimized for performance.\n4.Integration: Easily integrates with other scientific libraries like SciPy and pandas.\n5.Memory Efficiency: Uses less memory than Python lists, making it ideal for large datasets.\n    \n>>These features make NumPy essential for scientific computing and data analysis in Python.\n\n'

In [43]:
#Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
'''
>>np.mean():

1.Purpose: Calculates the arithmetic mean (average) of the elements along a specified axis or of the entire array if no axis is specified.
2.Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=False)
3.Key Points:
>>Axis Handling: You can specify the axis along which to compute the mean. If no axis is specified, it computes the mean of the flattened array.
>>Weights: np.mean() does not support weighting. All elements are treated equally.
>>Usage: Use np.mean() when you need to calculate a simple average without considering any weights.
4.Example:
import numpy as np
arr = np.array([1, 2, 3, 4])
mean = np.mean(arr)

>>np.average():

1.Purpose: Calculates the weighted average of the elements along a specified axis or of the entire array if no axis is specified.
2.Syntax:np.average(array, axis=None, weights=None, returned=False)
3.Key Points:
>>Weights: np.average() allows you to provide a weights array. Each element in the input array can be assigned a weight, and the function computes the weighted average accordingly.
>>Returned Sum of Weights: If returned=True, np.average() returns a tuple of the weighted average and the sum of the weights.
>>Axis Handling: Like np.mean(), you can specify the axis along which to compute the average.
>>Usage: Use np.average() when you need to calculate a weighted average where different elements have different levels of importance.
4.Example:
import numpy as np
arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
weighted_average = np.average(arr, weights=weights)


>>Basic Average: Both np.mean() and np.average() can compute a simple mean. However, np.mean() is more straightforward and should be used when no weighting is involved.
>>Weighted Average: Only np.average() allows for weighting, making it suitable for scenarios where certain elements should contribute more or less to the final average.

>>Use np.mean(): When you need a straightforward arithmetic mean without any weights.
>>Use np.average(): When you need to compute a weighted average, or if you want to obtain the sum of the weights alongside the weighted average.
'''


'\n>>np.mean():\n\n1.Purpose: Calculates the arithmetic mean (average) of the elements along a specified axis or of the entire array if no axis is specified.\n2.Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=False)\n3.Key Points:\n>>Axis Handling: You can specify the axis along which to compute the mean. If no axis is specified, it computes the mean of the flattened array.\n>>Weights: np.mean() does not support weighting. All elements are treated equally.\n>>Usage: Use np.mean() when you need to calculate a simple average without considering any weights.\n4.Example:\nimport numpy as np\narr = np.array([1, 2, 3, 4])\nmean = np.mean(arr)\n\n>>np.average():\n\n1.Purpose: Calculates the weighted average of the elements along a specified axis or of the entire array if no axis is specified.\n2.Syntax:np.average(array, axis=None, weights=None, returned=False)\n3.Key Points:\n>>Weights: np.average() allows you to provide a weights array. Each element in the input array can be

In [1]:
#Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
'''
>>Reversing a 1D Array:
Method: Slicing with a step of -1
Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

The slicing operation [::-1] creates a new array that starts from the end of the original array and moves backwards to the beginning.


>>Reversing a 2D Array Along Different Axes
Reversing Along the Rows (Axis 1)
Method: Slicing with a step of -1 along the second axis
Example:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
reversed_rows = arr[:, ::-1]
print(reversed_rows)

The slicing operation [:, ::-1] reverses the order of elements in each row, leaving the row order unchanged.

>>Reversing Along the Columns (Axis 0)
Method: Slicing with a step of -1 along the first axis.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
reversed_columns = arr[::-1, :]
print(reversed_columns)

The slicing operation [::, -1] reverses the order of the rows while leaving the elements within each row unchanged.

>>Reversing Both Axes (Both Rows and Columns)
Method: Slicing with a step of -1 along both axes.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
reversed_both = arr[::-1, ::-1]
print(reversed_both)

The slicing operation [::, -1], [::, -1] reverses the array both row-wise and column-wise, resulting in a completely reversed array.

'''

'\n>>Reversing a 1D Array:\nMethod: Slicing with a step of -1\nExample:\nimport numpy as np\narr = np.array([1, 2, 3, 4, 5])\nreversed_arr = arr[::-1]\nprint(reversed_arr)\n\nThe slicing operation [::-1] creates a new array that starts from the end of the original array and moves backwards to the beginning.\n\n\n>>Reversing a 2D Array Along Different Axes\nReversing Along the Rows (Axis 1)\nMethod: Slicing with a step of -1 along the second axis\nExample:\nimport numpy as np\narr = np.array([[1, 2, 3],\n                [4, 5, 6],\n                [7, 8, 9]])\nreversed_rows = arr[:, ::-1]\nprint(reversed_rows)\n\nThe slicing operation [:, ::-1] reverses the order of elements in each row, leaving the row order unchanged.\n\n>>Reversing Along the Columns (Axis 0)\nMethod: Slicing with a step of -1 along the first axis.\nimport numpy as np\narr = np.array([[1, 2, 3],\n                [4, 5, 6],\n                [7, 8, 9]])\nreversed_columns = arr[::-1, :]\nprint(reversed_columns)\n\nThe sl

In [ ]:
# How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
'''
>>To determine the data type of elements in a NumPy array, you can use the dtype attribute. This attribute returns an object that describes the data type of the array elements.
Example:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)
arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype)

>>Data types are crucial in memory management and performance:

1.Memory Management: The data type of an array determines the memory each element consumes. Using smaller data types (e.g., int32 vs. int64) reduces memory usage, which is important for handling large datasets efficiently.
2.Performance: Operations on smaller data types are generally faster because they require fewer CPU cycles and allow better cache utilization. Choosing the right data type can significantly enhance the speed and efficiency of computations.

In [ ]:
# Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''
Define:
ndarray (N-dimensional array) is the core data structure in NumPy, representing a multidimensional, homogeneous array of fixed-size items. Each element in an ndarray has the same data type, and the array itself can have one or more dimensions.

Key Features:
Homogeneity:All elements in an ndarray have the same data type (e.g., all integers, all floats). This homogeneity allows for efficient storage and processing.
Multidimensionality:ndarrays can have any number of dimensions, from 1D (like a list) to 2D (like a matrix) and beyond. The shape of an array is defined by the number of elements along each dimension (e.g., a 3x3 matrix is a 2D array with shape (3, 3)).
Efficient Memory Layout:ndarrays are stored in contiguous blocks of memory, which makes them much more memory-efficient and faster for operations than standard Python lists, especially for large datasets.
Slicing and Indexing:ndarrays offer advanced slicing and indexing capabilities, allowing you to access and modify subsets of data efficiently.
Broadcasting:ndarrays support broadcasting, a powerful mechanism that allows operations on arrays of different shapes without needing to duplicate data. For example, you can add a 1D array to a 2D array directly.


>>Differences from Standard Python Lists:
Data Type Consistency:
ndarray: All elements must be of the same data type, ensuring homogeneity.
Python List: Can contain elements of different data types (e.g., integers, floats, strings), leading to flexibility but less efficiency.

Memory Efficiency:
ndarray: Stored in contiguous memory, which makes them more memory-efficient.
Python List: Stored as an array of pointers to objects, which is less memory-efficient.

Performance:
ndarray: Operations are faster due to vectorization and the contiguous memory layout.
Python List: Slower for large datasets because operations require explicit loops and elements are scattered in memory.

Multidimensionality:
ndarray: Naturally supports multidimensional arrays.
Python List: Can be nested to create multidimensional structures, but handling them is less intuitive and less efficient.

Functionality:
ndarray: Comes with a rich set of mathematical and statistical functions optimized for array operations.
Python List: Lacks built-in mathematical operations, requiring external libraries or manual implementation.
'''

In [ ]:
#Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''

NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations:

1.Memory Efficiency: NumPy arrays are stored in contiguous memory and have a fixed data type, making them more memory-efficient than Python lists.

2.Speed: NumPy supports vectorized operations, allowing for faster element-wise calculations without explicit loops. It also uses optimized, low-level (C and Fortran) implementations for mathematical functions.

3.Broadcasting: NumPy allows operations on arrays of different shapes without manual size adjustments, further enhancing speed and reducing complexity.

4.Efficient Iteration: Iterations in NumPy are faster due to reduced overhead compared to Python's interpreted loops.
'''


In [4]:
#Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

'''
>>vstack() Function

Purpose: Stacks arrays vertically (row-wise).
Syntax:
numpy.vstack(tup)
Where tup is a sequence of arrays to be stacked.

Requirements:
Arrays must have the same shape along all dimensions except the first

Example:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

result = np.vstack((arr1, arr2))
print(result)


>>hstack() Function

Purpose: Stacks arrays horizontally (column-wise).
Syntax: numpy.hstack(tup)
Where tup is a sequence of arrays to be stacked.

Requirements:

Arrays must have the same shape along all dimensions except the second.

Example:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

result = np.hstack((arr1, arr2))
print(result)
'''

'\n>>vstack() Function\n\nPurpose: Stacks arrays vertically (row-wise).\nSyntax:\nnumpy.vstack(tup)\nWhere tup is a sequence of arrays to be stacked.\n\nRequirements:\nArrays must have the same shape along all dimensions except the first\n\nExample:\nimport numpy as np\n\narr1 = np.array([[1, 2, 3], [4, 5, 6]])\narr2 = np.array([[7, 8, 9], [10, 11, 12]])\n\nresult = np.vstack((arr1, arr2))\nprint(result)\n\n\n>>hstack() Function\n\nPurpose: Stacks arrays horizontally (column-wise).\nSyntax: numpy.hstack(tup)\nWhere tup is a sequence of arrays to be stacked.\n\nRequirements:\n\nArrays must have the same shape along all dimensions except the second.\n\nExample:\nimport numpy as np\n\narr1 = np.array([[1, 2, 3], [4, 5, 6]])\narr2 = np.array([[7, 8, 9], [10, 11, 12]])\n\nresult = np.hstack((arr1, arr2))\nprint(result)\n'

In [ ]:
# Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
'''
>>The fliplr() and flipud() methods in NumPy are used to reverse the order of elements in an array along specific axes.

1.fliplr()
Purpose: Flips the array left-to-right, reversing the order of columns.
Syntax:numpy.fliplr(m)............Where m is the array to be flipped.
Effect on Dimensions:
1D Array: Not applicable, as fliplr() requires at least a 2D array.
2D Array: Reverses the columns. The rows remain unchanged.
Higher-Dimensional Arrays: fliplr() operates on the last two dimensions. For instance, if you have a 3D array, fliplr() will reverse the columns for each 2D slice of the array.

Example:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flipped_arr = np.fliplr(arr)
print(flipped_arr)

2.flipud()
Purpose: Flips the array up-to-down, reversing the order of rows.
Syntax:numpy.flipud(m)..........Where m is the array to be flipped.
Effect on Dimensions:
1D Array: Not applicable, as flipud() requires at least a 2D array.
2D Array: Reverses the rows. The columns remain unchanged.
Higher-Dimensional Arrays: flipud() operates on the first two dimensions. For example, in a 3D array, flipud() will reverse the rows for each 2D slice along the third dimension.

Example:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flipped_arr = np.flipud(arr)
print(flipped_arr)
'''


In [ ]:
#Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''
>>Functionality of array_split():
Syntax:
numpy.array_split(ary, indices_or_sections, axis=0)
ary: The input array to be split.
indices_or_sections: If an integer n, it splits the array into n sub-arrays. If a list of indices, the array is split at those indices.
axis: The axis along which to split the array. The default is 0 (split along rows for a 2D array).

>>Handling Uneven Splits
When the array cannot be evenly divided into the specified number of sections, array_split() ensures that the split is as even as possible. The sub-arrays will differ in size by at most one element.

>>Example with an Integer Number of Sections:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
split_arr = np.array_split(arr, 3)
print(split_arr)


>>Example with a List of Indices:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
split_arr = np.array_split(arr, [2, 5])
print(split_arr)

'''


In [1]:
#Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''
Vectorization and broadcasting are two powerful concepts in NumPy that significantly contribute to efficient array operations. They help in optimizing performance and reducing the complexity of code when dealing with large datasets.

1.Vectorization:
Concept:
Vectorization refers to the process of applying operations directly to entire arrays or large blocks of data at once, without the need for explicit loops in the code. This approach leverages low-level optimizations implemented in C or Fortran, allowing these operations to be executed much faster than traditional Python loops.

Example:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr + 10
print(result)

Benefits:
>>Performance: Vectorized operations are much faster than manually iterating over arrays in Python.
>>Simplicity: The code is easier to read and write, as it avoids explicit loops.


2.Broadcasting
Concept:
Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array along the necessary dimensions to match the shape of the larger array. This allows for operations that would otherwise require complex handling of shapes and dimensions.

Rules:
>>If the arrays differ in the number of dimensions, the smaller array is padded with ones on its left side.
>>If the shape of the arrays does not match along a dimension, the smaller array's dimension is stretched to match the larger one.
>>If the arrays cannot be broadcasted together based on these rules, an error is raised.

Example:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)

Benefits:
>>Memory Efficiency: Broadcasting avoids the need to create large, repeated arrays to perform element-wise operations, saving memory.
>>Performance: Operations using broadcasting are faster because they utilize the underlying optimized C and Fortran libraries of NumPy.


>>Contribution to Efficient Array Operations
1.Speed: Both vectorization and broadcasting leverage low-level optimizations, allowing operations to be executed at compiled speeds, which are significantly faster than interpreted Python loops.
2.Memory Efficiency: Broadcasting allows operations on different-sized arrays without creating intermediate copies, which is more memory-efficient.
3.Conciseness: Code that utilizes vectorization and broadcasting is often much shorter and easier to understand, reducing the likelihood of errors and making maintenance easier.


'''


"\nVectorization and broadcasting are two powerful concepts in NumPy that significantly contribute to efficient array operations. They help in optimizing performance and reducing the complexity of code when dealing with large datasets.\n\n1.Vectorization:\nConcept:\nVectorization refers to the process of applying operations directly to entire arrays or large blocks of data at once, without the need for explicit loops in the code. This approach leverages low-level optimizations implemented in C or Fortran, allowing these operations to be executed much faster than traditional Python loops.\n\nExample:\nimport numpy as np\narr = np.array([1, 2, 3, 4])\nresult = arr + 10\nprint(result)\n\nBenefits:\n>>Performance: Vectorized operations are much faster than manually iterating over arrays in Python.\n>>Simplicity: The code is easier to read and write, as it avoids explicit loops.\n\n\n2.Broadcasting\nConcept:\nBroadcasting is a mechanism that allows NumPy to perform operations on arrays of d

# Practical Questions:

In [ ]:
# Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np
arr = np.random.randint(1, 101, size=(3, 3))
transposed_arr = arr.T
arr, transposed_arr

In [24]:
#Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
array_1d = np.arange(10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_2x5.reshape(5, 2)
array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [31]:
#Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np
array_4x4 = np.random.rand(4, 4)
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
array_with_border

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33405956, 0.20375242, 0.26213591, 0.45367142,
        0.        ],
       [0.        , 0.44405674, 0.98733152, 0.59739131, 0.71373641,
        0.        ],
       [0.        , 0.52600279, 0.0771553 , 0.71882292, 0.26885142,
        0.        ],
       [0.        , 0.64465004, 0.18388421, 0.10551213, 0.77935878,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [34]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5
import numpy as np
array_step = np.arange(10, 65, 5)
array_step

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [36]:
#Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
import numpy as np
string_array = np.array(['python', 'numpy', 'pandas'])
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
print("Original Array:", string_array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [37]:
#Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
words_array = np.array(['hello', 'world', 'numpy'])
spaced_words_array = np.char.join(' ', words_array)
print("Original Array:", words_array)
print("Spaced Characters Array:", spaced_words_array)


Original Array: ['hello' 'world' 'numpy']
Spaced Characters Array: ['h e l l o' 'w o r l d' 'n u m p y']


In [38]:
#Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
addition_result = array_2d_1 + array_2d_2
subtraction_result = array_2d_1 - array_2d_2
multiplication_result = array_2d_1 * array_2d_2
division_result = array_2d_1 / array_2d_2
print("Array 1:")
print(array_2d_1)
print("\nArray 2:")
print(array_2d_2)
print("\nElement-wise Addition:")
print(addition_result)
print("\nElement-wise Subtraction:")
print(subtraction_result)
print("\nElement-wise Multiplication:")
print(multiplication_result)
print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [39]:
#Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [40]:
#Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np
array = np.random.randint(0, 1001, size=100)
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True
primes = [num for num in array if is_prime(num)]
print("Array:", array)
print("Prime numbers in the array:", primes)


Array: [361 135 369 214 150 128 848 158 494 819 965 395 560  31 529 804 732 407
 476 348 221 831 165 165 285 848 672 384 943  37 596  13 776 770 528 233
 870 261 630 216 937 862 559 514 332 369 161 578 247 196 961 861 595 612
 801 611  24 336 639 964 166 626 673 793  73  88 328  74 240 318 720 241
 598 271 562 199 394 118  52 674 972 748 736 736 855 758 887 687 932  74
 669 433 617  10 357 532 650 184 444 215]
Prime numbers in the array: [31, 37, 13, 233, 937, 673, 73, 241, 271, 199, 887, 433, 617]


In [42]:
#Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np
daily_temperatures = np.random.randint(0, 101, size=30)  
weekly_temperatures = daily_temperatures.reshape(5,6)
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("Daily temperatures for the month:", daily_temperatures)
print("Weekly averages:", weekly_averages)

Daily temperatures for the month: [93 19 26 66 63 55 95 13 33 72 23  1 95 28 46 23 44 81 21 44 34 28 50 39
 69 73 67 23 49 26]
Weekly averages: [53.66666667 39.5        52.83333333 36.         51.16666667]
